export const StoredProcedureDefine = {
  VIEW_COST_OF_BILL: "VIEW_COST_OF_BILL",
  VIEW_TOP_20_BOOK: "VIEW_TOP_20_BOOK",
  VIEW_TOP_20_BOOK_CATEGORY: "VIEW_TOP_20_BOOK_CATEGORY",
  VIEW_BOOK_BY_ID: "VIEW_BOOK_BY_ID",
  CREATE_BOOK: "CREATE_BOOK",
  SEARCH_BOOK_BY_TITLE: "SEARCH_BOOK_BY_TITLE",
  ADD_TO_CART: "ADD_TO_CART",
  VIEW_BOOK_IN_CART: "View_Book_In_Cart",
  ADD_TO_BILL_AND_BILL_DETAIL: "ADD_BILL_DETAIL_TO_BILL",
  CREATE_BILL: "CREATE_BILL",
  ADD_BILL_DETAIL_TO_BILL: "ADD_BILL_DETAIL_TO_BILL",
  VIEW_ALL_MY_BILL_PENDING: "VIEW_ALL_MY_BILL_PENDING",
};