export const StoredProcedureDefine = {
  VIEW_COST_OF_BILL: "VIEW_COST_OF_BILL",
  VIEW_TOP_20_BOOK: "VIEW_TOP_20_BOOK",
  VIEW_TOP_20_BOOK_CATEGORY: "VIEW_TOP_20_BOOK_CATEGORY",
  VIEW_BOOK_BY_ID: "VIEW_BOOK_BY_ID",
  CREATE_BOOK: "CREATE_BOOK",
  SEARCH_BOOK_BY_TITLE: "SEARCH_BOOK_BY_TITLE",
};