USE BOOKSTORE_INDX
GO

--Chỉ mục cho bảng Book 
CREATE INDEX INDX_AUTHOR_ID ON BOOK(AUTHOR_ID)
CREATE INDEX INDX_PUBLISHER_ID ON BOOK(PUBLISHER_ID)
CREATE INDEX INDX_CATEGORY_IN ON BOOK(CATEGORY_ID)

--Chỉ mục cho bảng Author 
CREATE INDEX INDX_A_NAME ON AUTHOR(A_NAME)

--Chỉ mục cho bảng Publisher 
CREATE INDEX INDX_P_NAME ON PUBLISHER(P_NAME)

--Chỉ mục cho bảng Category 
CREATE INDEX INDX_TITLE ON CATEGORY(TITLE)

--Chỉ mục cho bảng Bill
CREATE INDEX INDX_CUSTOMER_ID ON BILL(CUSTOMER_ID)
CREATE INDEX INDX_CREATED_DATE ON BILL(CREATED_DATE)
CREATE INDEX INDX_BILL_TOTAL_COST ON BILL(BILL_TOTAL_COST)
CREATE INDEX INDX_B_STATUS ON BILL(B_STATUS)
CREATE INDEX INDX_EMPLOYEE_ID ON BILL(EMPLOYEE_ID)
CREATE INDEX [INDX_B_STATUS]
ON [dbo].[BILL] ([B_STATUS])
INCLUDE ([CREATED_DATE],[EMPLOYEE_ID],[CUSTOMER_ID],[BILL_TOTAL_COST])

DROP INDEX BILL.[INDX_B_STATUS]
--Chỉ mục cho bảng Employee 
CREATE INDEX INDX_E_NAME ON EMPLOYEE(E_NAME)