use BOOKSTORE
go

CREATE   PROCEDURE ADD_BILL_DETAIL_TO_BILL @BILL_ID INT, @BOOK_ID INT, @QUANTITY INT AS
DECLARE @PRICE INT
SELECT @PRICE = PRICE
FROM BOOK
WHERE BOOK_ID = @BOOK_ID
INSERT INTO BILL_DETAIL (BOOK_ID, BILL_ID, QUANTITY, PRICE)
VALUES (@BOOK_ID, @BILL_ID, @QUANTITY, @PRICE)
go

CREATE   PROCEDURE ADD_TO_BILL_AND_BILL_DETAIL
 @BOOK_ID INT,
 @QUANTITY INT
 AS
 INSERT INTO BILL(CREATED_DATE,B_STATUS,EMPLOYEE_ID,CUSTOMER_ID,BILL_TOTAL_COST) VALUES  (GETDATE(),'0',NULL,'1','0')
 DECLARE @BILL_ID INT
 SELECT @BILL_ID=  MAX(BILL_ID) FROM BILL
 DECLARE @PRICE INT
 SELECT @PRICE=PRICE FROM BOOK WHERE BOOK_ID=@BOOK_ID
 INSERT INTO BILL_DETAIL (BOOK_ID,BILL_ID,QUANTITY,PRICE) VALUES(@BOOK_ID,@BILL_ID,@QUANTITY,@PRICE)
go

CREATE   PROCEDURE
    ADD_TO_CART @CUSTOMER_ID INT, @BOOK_ID INT, @QUANTITY INT AS
INSERT INTO CART
VALUES (@CUSTOMER_ID, @BOOK_ID, @QUANTITY)
go

CREATE   PROCEDURE CHECKOUT_BILL
@BILL_ID INT
AS
SELECT B.BILL_ID,B.CREATED_DATE,B.BILL_TOTAL_COST 
 FROM BILL B 
 WHERE B.BILL_ID=@BILL_ID
go

create   procedure CREATE_BILL @EMPLOYEE_ID INT, @CUSTOMER_ID INT AS
BEGIN
    INSERT INTO BILL(CREATED_DATE, B_STATUS, EMPLOYEE_ID, CUSTOMER_ID, BILL_TOTAL_COST)
    OUTPUT INSERTED.BILL_ID
    VALUES (GETDATE(), '0', @EMPLOYEE_ID, @CUSTOMER_ID, '0')
END
go

CREATE   PROCEDURE CREATE_BOOK(
    @TITLE NVARCHAR(50),
    @AUTHOR_ID INT,
    @PUBLISHER_ID INT,
    @CATEGORY_ID INT,
    @DESCRIPTION VARCHAR(MAX),
    @COVER_URL VARCHAR(MAX),
    @PRICE INT,
    @SALE_PRICE INT,
    @STOCK INT
)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO BOOK(B_NAME,
                     AUTHOR_ID,
                     CATEGORY_ID,
                     PUBLISHER_ID,
                     B_DESCRIPTION,
                     COVER_URL,
                     PRICE,
                     SALE_PRICE,
                     STOCK)
    VALUES (@TITLE,
            @AUTHOR_ID,
            @CATEGORY_ID,
            @PUBLISHER_ID,
            @DESCRIPTION,
            @COVER_URL,
            @PRICE,
            @SALE_PRICE,
            @STOCK);
END
go

