CREATE   PROCEDURE DELETE_BILL_DETAIL
 @BILL_ID INT,
 @BOOK_ID INT
 AS
 DELETE FROM BILL_DETAIL WHERE BOOK_ID=@BOOK_ID AND BILL_ID=@BILL_ID
 DELETE FROM BILL WHERE BILL_ID=@BILL_ID
go

CREATE   PROCEDURE DELETE_BILL_DETAIL_AND_BILL @BILL_ID INT
AS
DELETE
FROM BILL_DETAIL
WHERE BILL_ID = @BILL_ID
DELETE
FROM BILL
WHERE BILL_ID = @BILL_ID
go

CREATE   PROCEDURE SEARCH_BOOK_BY_TITLE @SEARCH_STRING nvarchar(50)
AS
SELECT *
FROM BOOK
WHERE BOOK.B_NAME LIKE '%' + @SEARCH_STRING + '%'
go

CREATE   PROCEDURE UPDATE_QUANTITY
@BOOK_ID INT,
@BILL_ID INT,
@QUANTITY INT
AS
UPDATE BILL_DETAIL
SET QUANTITY=@QUANTITY
WHERE BILL_ID=@BILL_ID AND BOOK_ID=@BOOK_ID
go

CREATE   PROCEDURE VIEW_ALL_MY_BILL @CUSTOMER_ID INT
AS
SELECT *
FROM BILL JOIN CUSTOMER C on BILL.CUSTOMER_ID = C.CUSTOMER_ID
WHERE BILL.CUSTOMER_ID = @CUSTOMER_ID
go

CREATE   PROCEDURE VIEW_ALL_MY_BILL_PENDING @CUSTOMER_ID INT
AS
SELECT *
FROM BILL JOIN CUSTOMER C on BILL.CUSTOMER_ID = C.CUSTOMER_ID
WHERE BILL.CUSTOMER_ID = @CUSTOMER_ID AND B_STATUS = 0
go

CREATE   PROCEDURE VIEW_BOOK_BY_ID @book_id INT
AS
SELECT B.BOOK_ID, B.B_NAME, B.PRICE, B.CATEGORY_ID, B.COVER_URL, B.STOCK, A.A_NAME AS AUTHOR_NAME, C.TITLE AS CATEGORY_NAME, B.TOTAL_SOLD_BOOK
FROM BOOK B JOIN AUTHOR A
on B.AUTHOR_ID = A.AUTHOR_ID
    JOIN CATEGORY C on C.CATEGORY_ID = B.CATEGORY_ID
where B.BOOK_ID = @book_id
ORDER BY B.BOOK_ID DESC;
go

CREATE   PROCEDURE VIEW_COST_OF_BILL
@BILL_ID INT
AS
SELECT BILL_TOTAL_COST FROM BILL WHERE BILL_ID=@BILL_ID
go

--- Xem lịch sử đặt hàng
CREATE   PROCEDURE VIEW_HISTORY_BILL
@CUSTOMER_ID INT
AS 
SELECT BO.BOOK_ID,BD.QUANTITY,BD.PRICE,B.CREATED_DATE
FROM BILL B JOIN BILL_DETAIL BD 
ON B.BILL_ID=BD.BILL_ID
JOIN BOOK BO ON BO.BOOK_ID=BD.BOOK_ID
ORDER BY B.CREATED_DATE DESC
go

CREATE   PROCEDURE VIEW_TOP_20_BOOK
AS
SELECT TOP (20) B.BOOK_ID, B.B_NAME, B.PRICE, B.CATEGORY_ID, B.COVER_URL, A.A_NAME AS AUTHOR_NAME, C.TITLE AS CATEGORY_NAME, B.TOTAL_SOLD_BOOK
FROM BOOK B
         JOIN AUTHOR A on B.AUTHOR_ID = A.AUTHOR_ID
         JOIN CATEGORY C on C.CATEGORY_ID = B.CATEGORY_ID
ORDER BY B.BOOK_ID DESC;
go

CREATE   PROCEDURE VIEW_TOP_20_BOOK_CATEGORY @CATEGORY_ID INT
AS
SELECT TOP (20) B.BOOK_ID,
                B.B_NAME,
                B.PRICE,
                B.CATEGORY_ID,
                B.COVER_URL,
                A.A_NAME AS AUTHOR_NAME,
                C.TITLE  AS CATEGORY_NAME,
                B.TOTAL_SOLD_BOOK
FROM BOOK B
         JOIN AUTHOR A on B.AUTHOR_ID = A.AUTHOR_ID
         JOIN CATEGORY C on C.CATEGORY_ID = B.CATEGORY_ID
WHERE C.CATEGORY_ID = @CATEGORY_ID

ORDER BY B.BOOK_ID DESC;
go

CREATE   PROCEDURE View_Book_In_Cart @CUSTOMER_ID INT
AS
SELECT B.BOOK_ID,
       B_NAME,
       B_DESCRIPTION,
       PRICE,
       SALE_PRICE,
       STOCK,
       PUBLISHED_DATE,
       B_STATUS,
       PUBLISHER_ID,
       WAREHOUSE_ID,
       TOTAL_SOLD_BOOK,
       COVER_URL,
       CATEGORY_ID,
       A.AUTHOR_ID,
       SLUG,
       A_NAME,
       INTRO,
       CD.Quantity
FROM BOOK B
         JOIN AUTHOR A on A.AUTHOR_ID = B.AUTHOR_ID
         JOIN CART CD on B.BOOK_ID = CD.BOOK_ID
WHERE B.BOOK_ID IN (SELECT CART.BOOK_ID FROM CART WHERE CUSTOMER_ID = @CUSTOMER_ID)